In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [4]:
# 1. 데이터 준비 - 독립변수와 종속변수를 나누어 데이터를 준비해야 한다.

파일경로 = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
데이터 = pd.read_csv(파일경로)

# 데이터를 잘 읽어들였는지 확인한다.
print(데이터.columns)
데이터.head()

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [5]:
# 원핫인코딩
인코딩 = pd.get_dummies(데이터)
print(인코딩.columns)
인코딩.head()

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [8]:
# 독립변수와 종속변수 나누기
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor',
       '품종_virginica']]

print(독립.shape,종속.shape) # shape를 이용해서 항상 눈으로 체크해준다.

(150, 4) (150, 3)


In [11]:
# 2. 모델의 구조를 만든다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation= 'swish')(X)
H = tf.keras.layers.Dense(8, activation= 'swish')(H)
H = tf.keras.layers.Dense(8, activation= 'swish')(H) 
Y = tf.keras.layers.Dense(3, activation = 'softmax')(H) # 분류 모델 : softmax -> 0과 1 사이의 결과값을 알 수 있다.
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy') # 분류 모델 = categorical_crossentropy, accuracy는 정확도를 보여준다.

In [12]:
# 3. 모델을 학습(FIT)시킨다.
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 1s 2ms/step - loss: 0.9997 - accuracy: 0.3791
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.9828 - accuracy: 0.3238
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.9265 - accuracy: 0.3707
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.9364 - accuracy: 0.3316
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.9332 - accuracy: 0.3283
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8909 - accuracy: 0.3411
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8841 - accuracy: 0.3595
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8967 - accuracy: 0.3288
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8467 - accuracy: 0.4036
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8377 - accuracy: 0.3801


In [14]:
# 4. 모델을 이용한다
model.predict(독립[0:5]) # 0번째부터 5번째까지만 사용한다.

array([[0.3511789 , 0.39215955, 0.25666147],
       [0.362     , 0.38573295, 0.252267  ],
       [0.36156446, 0.38197035, 0.25646517],
       [0.3586471 , 0.38180867, 0.25954425],
       [0.34933093, 0.39042336, 0.26024568]], dtype=float32)

In [15]:
# 5. 학습한 가중치
model.get_weights() 

[array([[ 0.06131155, -0.05509567, -0.39325434, -0.06655996, -0.24581315,
          0.20763488,  0.12896633, -0.27253163],
        [ 0.0736917 , -0.5205066 , -0.13493809, -0.38900834,  0.38844863,
          0.59516525, -0.34238642, -0.44468668],
        [ 0.5285343 , -0.14404485, -0.59426737,  0.31017664,  0.28117093,
          0.4713631 , -0.28934342, -0.28887337],
        [ 0.00079643, -0.4365281 , -0.6353717 ,  0.095545  ,  0.7283959 ,
          0.18000461, -0.09960534, -0.70305026]], dtype=float32),
 array([ 0.04644314,  0.05399561,  0.01296756,  0.04582613, -0.0057075 ,
        -0.00761372,  0.01668401,  0.01797974], dtype=float32),
 array([[ 0.23568237, -0.11508439,  0.4908043 ,  0.37381855, -0.20855816,
         -0.10773718, -0.5556361 ,  0.08878138],
        [ 0.32480162, -0.22885823, -0.49730763,  0.64275944, -0.09598392,
          0.49565342, -0.09273367, -0.14751267],
        [ 0.64166605,  0.00424059, -0.4899839 ,  0.10698231, -0.11617539,
         -0.17159061,  0.34171316,